#!/bin/bash

# COMMON DIRECTORIES
export JDIR=~/dev/javadir/
export OPENSRC=~/dev/opensrc/

# ALIAS
alias EDITOR=nvim
alias vi=nvim
alias vim=nvim

alias l="ls"
alias ll="ls -lrth"
alias lr="ls -1R"
alias la="ls -la"

alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../../"

export JDTLS_JVM_ARGS="-javaagent:$HOME/.local/share/nvim/mason/packages/jdtls/lombok.jar"

# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

